#!/bin/bash

#This script is the user-data file to install and launch NGINX

sudo apt update -y
sudo apt upgrade -y
sudo apt install -y apache2
sudo systemctl start apache2
sudo systemctl enable apache2
