#!/bin/bash

#This script is the user-data file to install and launch NGINX

sudo apt update -y
sudo sleep 10
sudo apt upgrade -y
sudo apt install apache2 -y
sudo systemctl start apache2
sudo systemctl enable apache2
