#!/bin/bash

#This script is the user-data file to install and launch NGINX

sudo apt update -y
sudo apt upgrade -y
sudo apt install apache2 -y
sudo systemctl apache2 start
sudo systemctl apache2 enable
